artifacts_root: artifacts

data_injestion:
  root_directory: artifacts/data_injestion
  source_URL: "https://drive.google.com/file/d/17TCF4Q0VmWnpfeML-3O5npF2-C4UYlhe/view?usp=sharing"
  local_data_file: artifacts/data_injestion/data.zip
  unzip_dir: artifacts/data_injestion
  
