artifacts_root: artifacts

data_injestion:
  root_directory: artifacts/data_injestion
  source_URL: "https://drive.google.com/file/d/17TCF4Q0VmWnpfeML-3O5npF2-C4UYlhe/view?usp=sharing"
  local_data_file: artifacts/data_injestion/data.zip
  unzip_dir: artifacts/data_injestion
  
prepare_base_model: 
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5